{
 "openapi": "3.1.0",
 "info": {
  "title": "OWJ CRS Account Microservice",
  "description": "This is the API documentation for the OWJ CRS Account Service.",
  "version": "1.0.0"
 },
 "servers": [
  {
   "url": "https://account.owj.app/",
   "description": "Production environment"
  },
  {
   "url": "http://localhost:8000/",
   "description": "Local environment"
  }
 ],
 "paths": {
  "/api/account/v1/user": {
   "post": {
    "tags": [
     "User Account"
    ],
    "summary": "Create User Account",
    "description": "Type and Scope:\n\n- **Type**: AGENCY or BUSINESS User Set\n- **Scope**: USER_ACCOUNT:CREATE\n\nDescription:\n\n- **AGENCY_SUPERUSER**: Can create any type of user account, including other AGENCY users. Business is needed if the user type is BUSINESS_USER.\n- **AGENCY_USER**: Can create any type of user account, excluding other AGENCY users. Business is needed if the user type is BUSINESS_USER.\n- **BUSINESS_SUPERUSER and USER**: Can create only **BUSINESS_USER**. The busines[...]",
    "operationId": "create_user_account",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "USER_ACCOUNT:CREATE"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "User Account"
    ],
    "summary": "Get User Accounts",
    "description": "Type and Scope:\n\n- **Type**: AGENCY or BUSINESS User Set\n- **Scope**: USER_ACCOUNT:READ",
    "operationId": "get_user_accounts",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "USER_ACCOUNT:READ"
      ]
     }
    ]
   }
  },
  "/api/account/v1/user/me": {
   "get": {
    "tags": [
     "User Account"
    ],
    "summary": "Get My User Account",
    "description": "Type and Scope:\n\n- **Type**: Any User Set\n- **Scope**: None",
    "operationId": "get_my_user_account",
    "security": [
     {
      "OAuth2PasswordBearer": []
     }
    ]
   },
   "put": {
    "tags": [
     "User Account"
    ],
    "summary": "Update My User Account",
    "description": "Type and Scope:\n\n- **Type**: Any User Set\n- **Scope**: None",
    "operationId": "update_my_user_account",
    "security": [
     {
      "OAuth2PasswordBearer": []
     }
    ]
   }
  },
  "/api/account/v1/user/{id}": {
   "get": {
    "tags": [
     "User Account"
    ],
    "summary": "Get User Account",
    "description": "Type and Scope:\n\n- **Type**: AGENCY or BUSINESS User Set\n- **Scope**: USER_ACCOUNT:READ",
    "operationId": "get_user_account",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "USER_ACCOUNT:READ"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "User Account"
    ],
    "summary": "Update User Account",
    "description": "Type and Scope:\n\n- **Type**: Any User Set\n- **Scope**: USER_ACCOUNT:UPDATE\n\nDescription:\nAGENCY users can update any user account, excluding other AGENCY users. BUSINESS users can update only users of their business. REGULAR users can update only themselves.",
    "operationId": "update_user_account",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "USER_ACCOUNT:UPDATE"
      ]
     }
    ]
   }
  },
  "/api/account/v1/group": {
   "post": {
    "tags": [
     "User Group"
    ],
    "summary": "Create Group",
    "description": "Type and Scope:\n\n- **Type**: AGENCY  User Set\n- **Scope**: USER_GROUP:READ",
    "operationId": "create_group",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "USER_GROUP:CREATE"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "User Group"
    ],
    "summary": "Get Groups",
    "description": "Type and Scope:\n\n- **Type**: AGENCY  User Set\n- **Scope**: USER_GROUP:READ",
    "operationId": "get_groups",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "USER_GROUP:READ"
      ]
     }
    ]
   }
  },
  "/api/account/v1/group/me": {
   "get": {
    "tags": [
     "User Group"
    ],
    "summary": "Get My Groups",
    "description": "Type and Scope:\n\n- **Type**: Any User Set\n- **Scope**: None",
    "operationId": "get_my_groups",
    "security": [
     {
      "OAuth2PasswordBearer": []
     }
    ]
   }
  },
  "/api/account/v1/group/user/{user_id}": {
   "get": {
    "tags": [
     "User Group"
    ],
    "summary": "Get User Groups",
    "description": "Type and Scope:\n\n- **Type**: AGENCY AND BUSINESS User Set\n- **Scope**: None",
    "operationId": "get_user_groups",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "USER_GROUP:READ"
      ]
     }
    ]
   }
  },
  "/api/account/v1/group/{id}": {
   "get": {
    "tags": [
     "User Group"
    ],
    "summary": "Get Group",
    "description": "Type and Scope:\n\n- **Type**: AGENCY  User Set\n- **Scope**: USER_GROUP:READ",
    "operationId": "get_group",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "USER_GROUP:READ"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "User Group"
    ],
    "summary": "Update Group",
    "description": "Type and Scope:\n\n- **Type**: AGENCY  User Set\n- **Scope**: USER_GROUP:UPDATE",
    "operationId": "update_group",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "USER_GROUP:UPDATE"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "User Group"
    ],
    "summary": "Delete Group",
    "description": "Type and Scope:\n\n- **Type**: AGENCY  User Set\n- **Scope**: USER_GROUP:DELETE",
    "operationId": "delete_group",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "USER_GROUP:DELETE"
      ]
     }
    ]
   }
  },
  "/api/account/v1/group/{id}/add": {
   "post": {
    "tags": [
     "User Group"
    ],
    "summary": "Add User To Group",
    "description": "Type and Scope:\n\n- **Type**: AGENCY  User Set\n- **Scope**: USER_GROUP:ADD_USER",
    "operationId": "add_user_to_group",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "USER_GROUP:ADD_USER"
      ]
     }
    ]
   }
  },
  "/api/account/v1/group/{id}/remove": {
   "delete": {
    "tags": [
     "User Group"
    ],
    "summary": "Remove User From Group",
    "description": "Type and Scope:\n\n- **Type**: AGENCY  User Set\n- **Scope**: USER_GROUP:ADD_USER",
    "operationId": "remove_user_from_group",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "USER_GROUP:READ"
      ]
     }
    ]
   }
  },
  "/api/account/v1/business": {
   "post": {
    "tags": [
     "Business Account"
    ],
    "summary": "Create Business Account",
    "description": "Type and Scope:\n\n- **Type**: AGENCY User Set\n- **Scope**: BUSINESS_ACCOUNT:CREATE\n\nDescription:\n\nIf the provided phone number is already registered as a user, the user will be converted to a business user.\nThe users wallets will be assigned to the business.\n\nIf the provided phone number is not registered as a user, a new user will be created and assigned to the business.",
    "operationId": "create_business_account",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "BUSINESS_ACCOUNT:CREATE"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "Business Account"
    ],
    "summary": "List Business Accounts",
    "description": "Type and Scope:\n\n- **Type**: AGENCY User Set\n- **Scope**: BUSINESS_ACCOUNT:READ",
    "operationId": "list_business_accounts",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "BUSINESS_ACCOUNT:READ"
      ]
     }
    ]
   }
  },
  "/api/account/v1/business/me": {
   "get": {
    "tags": [
     "Business Account"
    ],
    "summary": "Get the business account of the current user ",
    "description": "Type and Scope:\n\n- **Type**: BUSINESS User Set\n- **Scope**: None",
    "operationId": "get_business_account_me",
    "security": [
     {
      "OAuth2PasswordBearer": []
     }
    ]
   }
  },
  "/api/account/v1/business/{id}": {
   "get": {
    "tags": [
     "Business Account"
    ],
    "summary": "Get Business Account",
    "description": "Type and Scope:\n\n- **Type**: AGENCY User Set\n- **Scope**: BUSINESS_ACCOUNT:READ",
    "operationId": "get_business_account",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "BUSINESS_ACCOUNT:READ"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Business Account"
    ],
    "summary": "Update Business Account",
    "description": "Type and Scope:\n\n- **Type**: AGENCY_AND_BUSINESS User Set\n- **Scope**: BUSINESS_ACCOUNT:UPDATE",
    "operationId": "update_business_account",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "BUSINESS_ACCOUNT:UPDATE"
      ]
     }
    ]
   }
  },
  "/api/account/v1/auth/password": {
   "post": {
    "tags": [
     "Authentication"
    ],
    "summary": "Password Login",
    "description": "This endpoint is used to get an access token for a user.\n\nThe access token is used to authenticate the user for all other endpoints.\n\nFuture requests should include the access token in the Authorization header.\n\nIf two-factor authentication is enabled, an OTP is sent to the user's phone number. The user must then retry the request with the OTP.",
    "operationId": "password_login"
   }
  },
  "/api/account/v1/auth/otp": {
   "post": {
    "tags": [
     "Authentication"
    ],
    "summary": "Get Totp",
    "description": "Get a Time-based One-Time Password (TOTP) for a user.\n\nIf the user does not exist, a new user is created.\n\nIf the user is not allowed to login with only OTP (OTP login is disabled), an error (E1015) is returned.",
    "operationId": "get_totp"
   }
  },
  "/api/account/v1/auth/otp/verify": {
   "post": {
    "tags": [
     "Authentication"
    ],
    "summary": "Totp Login",
    "description": "Verify the Time-based One-Time Password (TOTP) for a user.",
    "operationId": "totp_login"
   }
  },
  "/api/account/v1/auth/set-password": {
   "post": {
    "tags": [
     "Authentication"
    ],
    "summary": "Set Password",
    "description": "Set password for a user if the user has not set a password yet",
    "operationId": "set_password",
    "security": [
     {
      "OAuth2PasswordBearer": []
     }
    ]
   }
  },
  "/api/account/v1/auth/refresh": {
   "post": {
    "tags": [
     "Authentication"
    ],
    "summary": "Refresh Token",
    "description": "Refresh an access token\n\nThis endpoint is used to get a new access token using a refresh token.\n\nThe old refresh token is invalidated and a new refresh token is returned.",
    "operationId": "refresh_token"
   }
  },
  "/api/account/v1/auth/logout": {
   "post": {
    "tags": [
     "Authentication"
    ],
    "summary": "Logout",
    "description": "Logout a user\n\nThis endpoint is used to logout a user.\n\nThe refresh token is invalidated and the user is logged out.",
    "operationId": "logout"
   }
  },
  "/api/account/v1/wallet/transaction": {
   "post": {
    "tags": [
     "Wallet Transaction"
    ],
    "summary": "Create Wallet Transaction",
    "description": "Type and Scope:\n\n- **Type**: AGENCY User Set\n- **Scope**: WALLET_TRANSACTION:CREATE",
    "operationId": "create_wallet_transaction",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "WALLET_TRANSACTION:CREATE"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "Wallet Transaction"
    ],
    "summary": "Get Wallet Transactions",
    "description": "Type and Scope:\n\n- **Type**: AGENCY User Set\n- **Scope**: WALLET_TRANSACTION:READ",
    "operationId": "get_wallet_transactions",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "WALLET_TRANSACTION:READ"
      ]
     }
    ]
   }
  },
  "/api/account/v1/wallet/transaction/me": {
   "get": {
    "tags": [
     "Wallet Transaction"
    ],
    "summary": "Get My Wallet Transactions",
    "description": "Type and Scope:\n\n- **Type**: Any User Set\n- **Scope**: None",
    "operationId": "get_my_wallet_transactions",
    "security": [
     {
      "OAuth2PasswordBearer": []
     }
    ]
   }
  },
  "/api/account/v1/wallet/transaction/me/{id}": {
   "get": {
    "tags": [
     "Wallet Transaction"
    ],
    "summary": "Get My Wallet Transaction",
    "description": "Type and Scope:\n\n- **Type**: Any User Set\n- **Scope**: None",
    "operationId": "get_my_wallet_transaction",
    "security": [
     {
      "OAuth2PasswordBearer": []
     }
    ]
   }
  },
  "/api/account/v1/wallet/transaction/business/{business_id}": {
   "get": {
    "tags": [
     "Wallet Transaction"
    ],
    "summary": "Get Business Wallet Transactions",
    "description": "Type and Scope:\n\n- **Type**: AGENCY or Business User Set\n- **Scope**: WALLET_TRANSACTION:READ",
    "operationId": "get_business_wallet_transactions",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "WALLET_TRANSACTION:READ"
      ]
     }
    ]
   }
  },
  "/api/account/v1/wallet/transaction/{user_id}": {
   "get": {
    "tags": [
     "Wallet Transaction"
    ],
    "summary": "Get User Wallet Transactions",
    "description": "Type and Scope:\n\n- **Type**: Any User Set\n- **Scope**: None",
    "operationId": "get_user_wallet_transactions",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "WALLET_TRANSACTION:READ"
      ]
     }
    ]
   }
  },
  "/api/account/v1/wallet/me": {
   "get": {
    "tags": [
     "Wallet"
    ],
    "summary": "Get My Wallets",
    "description": "Type and Scope:\n\n- **Type**: Any User Set\n- **Scope**: None",
    "operationId": "get_my_wallets",
    "security": [
     {
      "OAuth2PasswordBearer": []
     }
    ]
   }
  },
  "/api/account/v1/wallet/me/{currency}": {
   "get": {
    "tags": [
     "Wallet"
    ],
    "summary": "Get My Wallet",
    "description": "Type and Scope:\n\n- **Type**: Any User Set\n- **Scope**: None",
    "operationId": "get_my_wallet",
    "security": [
     {
      "OAuth2PasswordBearer": []
     }
    ]
   }
  },
  "/api/account/v1/wallet/me/deposit": {
   "post": {
    "tags": [
     "Wallet"
    ],
    "summary": "Topoff My Wallet",
    "description": "Type and Scope:\n\n- **Type**: Any User Set\n- **Scope**: None",
    "operationId": "topoff_my_wallet",
    "security": [
     {
      "OAuth2PasswordBearer": []
     }
    ]
   }
  },
  "/api/account/v1/wallet/business/{business_id}": {
   "get": {
    "tags": [
     "Wallet"
    ],
    "summary": "Get Business Wallets",
    "description": "Type and Scope:\n\n- **Type**: AGENCY or BUSINESS User Set\n- **Scope**: WALLET_READ",
    "operationId": "get_business_wallets",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "WALLET:READ"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Wallet"
    ],
    "summary": "Update Business Wallet",
    "description": "Type and Scope:\n\n- **Type**: AGENCY User Set\n- **Scope**: WALLET:UPDATE",
    "operationId": "update_business_wallet",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "WALLET:UPDATE"
      ]
     }
    ]
   }
  },
  "/api/account/v1/wallet/{user_id}": {
   "get": {
    "tags": [
     "Wallet"
    ],
    "summary": "Get User Wallets",
    "description": "Type and Scope:\n\n- **Type**: AGENCY or BUSINESS User Set\n- **Scope**: WALLET_READ",
    "operationId": "get_user_wallets",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "WALLET:READ"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Wallet"
    ],
    "summary": "Update Wallet",
    "description": "Type and Scope:\n\n- **Type**: AGENCY User Set\n- **Scope**: WALLET:UPDATE",
    "operationId": "update_wallet",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "WALLET:UPDATE"
      ]
     }
    ]
   }
  },
  "/api/account/v1/wallet/{user_id}/{currency}": {
   "get": {
    "tags": [
     "Wallet"
    ],
    "summary": "Get User Wallet",
    "description": "Type and Scope:\n\n- **Type**: AGENCY or BUSINESS User Set\n- **Scope**: WALLET:READ",
    "operationId": "get_user_wallet",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "WALLET:READ"
      ]
     }
    ]
   }
  },
  "/api/account/v1/wallet/{user_id}/deposit": {
   "post": {
    "tags": [
     "Wallet"
    ],
    "summary": "Topoff User Wallet",
    "description": "Type and Scope:\n\n- **Type**: Any\n- **Scope**: None",
    "operationId": "topoff_user_wallet",
    "security": [
     {
      "OAuth2PasswordBearer": []
     }
    ]
   }
  },
  "/api/account/v1/ipg/callback/nextpay": {
   "get": {
    "tags": [
     "IPG"
    ],
    "summary": "Nextpay Callback",
    "operationId": "nextpay_callback"
   }
  },
  "/api/account/v1/ipg/transactions": {
   "get": {
    "tags": [
     "IPG"
    ],
    "summary": "List All Ipgs Transactions",
    "operationId": "list_all_ipgs_transactions",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "IPG_TRANSACTION:READ"
      ]
     }
    ]
   }
  },
  "/api/account/v1/ipg/transactions/{id}": {
   "get": {
    "tags": [
     "IPG"
    ],
    "summary": "Get Ipg Transaction",
    "operationId": "get_ipg_transaction",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "IPG_TRANSACTION:READ"
      ]
     }
    ]
   }
  },
  "/api/account/v1/ipg": {
   "post": {
    "tags": [
     "IPG"
    ],
    "summary": "Create Ipg",
    "description": "This Method is for creating a ipg.",
    "operationId": "create_ipg",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "IPG:CREATE"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "IPG"
    ],
    "summary": "List Ipgs",
    "operationId": "list_ipgs",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "IPG:READ"
      ]
     }
    ]
   }
  },
  "/api/account/v1/ipg/{id}": {
   "put": {
    "tags": [
     "IPG"
    ],
    "summary": "Update Ipg",
    "description": "This Method is for updating a ipg.",
    "operationId": "update_ipg",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "IPG:UPDATE"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "IPG"
    ],
    "summary": "Delete Ipg",
    "description": "This Method is for deleting a ipg.",
    "operationId": "delete_ipg",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "IPG:DELETE"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "IPG"
    ],
    "summary": "Get Ipg",
    "operationId": "get_ipg",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "IPG:READ"
      ]
     }
    ]
   }
  },
  "/api/account/v1/ipg/{ipg_id}/transactions": {
   "get": {
    "tags": [
     "IPG"
    ],
    "summary": "List Ipg Transactions",
    "operationId": "list_ipg_transactions",
    "security": [
     {
      "OAuth2PasswordBearer": [
       "IPG_TRANSACTION:READ"
      ]
     }
    ]
   }
  }
 },
 "components": {
  "securitySchemes": {
   "OAuth2PasswordBearer": {
    "type": "oauth2",
    "flows": {
     "password": {
      "scopes": {},
      "tokenUrl": "/api/account/v1/auth/oauth2"
     }
    }
   }
  }
 }
}